@extends('layouts.dashboard')
@section('title','Tracking')
@section('dashboard')
<div class="page-head"><div><div class="eyebrow">TRACKING</div><h1>Status barang publik</h1><p class="muted">Tracking Batch dikelola dari halaman Batch. Tracking manual dapat diedit atau dihapus dari sini.</p></div></div>
<form class="filters"><input class="input" name="q" value="{{ request('q') }}" placeholder="Batch / PO / item / tracking / negara">@include('partials.filter-actions')</form>
<div class="table-wrap"><table class="table"><thead><tr><th>Ref</th><th>Barang</th><th>Keterangan</th><th>Negara</th><th>Tracking</th><th>Status</th><th>Publik</th><th></th></tr></thead><tbody>
@forelse($shipments as $shipment)
<tr><td><strong>{{ $shipment->reference }}</strong></td><td>{{ $shipment->item_details }}</td><td>{{ $shipment->description_type }}</td><td>{{ $shipment->country->name }}</td><td>{{ $shipment->tracking_number ?: 'Belum tersedia' }}</td><td><span class="badge status-colored" style="--status-color:{{ \App\Services\OrderStatusService::color($shipment->status) }}">{{ \App\Services\OrderStatusService::label($shipment->status) }}</span></td><td>{{ $shipment->visible_publicly?'Ya':'Tidak' }}</td><td>@if(auth()->user()->isOwner() && !($shipment->source_type==='batch' && $shipment->source_id))<details><summary class="btn btn-soft btn-sm">Atur</summary><form method="post" action="{{ route('owner.tracking.update',$shipment) }}" class="card" style="margin-top:8px;min-width:min(560px,82vw)">@csrf @method('patch')<div class="form-grid"><div class="field"><label>Referensi</label><input class="input" name="reference" value="{{ $shipment->reference }}" required></div><div class="field"><label>Barang</label><input class="input" name="item_details" value="{{ $shipment->item_details }}" required></div><div class="field"><label>Keterangan</label><input class="input" name="description_type" value="{{ $shipment->description_type }}" required></div><div class="field"><label>Info</label><input class="input" name="info" value="{{ $shipment->info }}"></div><div class="field"><label>Tracking Number</label><input class="input" name="tracking_number" value="{{ $shipment->tracking_number }}"></div><div class="field"><label>Status</label><select class="select" name="status" required>@foreach(\App\Services\OrderStatusService::statuses() as $status)<option value="{{ $status }}" @selected($shipment->status===$status)>{{ \App\Services\OrderStatusService::label($status) }}</option>@endforeach</select></div><div class="field full"><label><input type="checkbox" name="visible_publicly" value="1" @checked($shipment->visible_publicly)> Tampilkan publik</label></div></div><button class="btn btn-primary btn-sm">Simpan</button></form><form method="post" action="{{ route('owner.tracking.destroy',$shipment) }}" data-confirm-title="Hapus permanen" data-confirm="Hapus tracking manual {{ $shipment->reference }} secara permanen? Tracking ini tidak berasal dari Batch sehingga aman dihapus tanpa mengubah Batch/order. Tindakan tidak dapat dibatalkan." style="margin-top:8px">@csrf @method('delete')<button class="btn btn-danger btn-sm">Hapus tracking</button></form></details>@else<span class="small muted">Dari Batch</span>@endif</td></tr>
@empty<tr><td colspan="8" class="empty">Tidak ada tracking yang cocok.</td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $shipments->links() }}</div>
@if(auth()->user()->isOwner())
<form class="card" style="margin-top:18px" method="post" action="{{ route('owner.tracking.store') }}">@csrf<h3>Tambah tracking manual</h3><div class="form-grid" style="margin-top:12px"><div class="field"><label>Sumber</label><select class="select" name="source_type"><option value="po">PO</option><option value="batch">Batch non-sistem / legacy</option></select></div><div class="field"><label>Batch / PO</label><input class="input" name="reference" value="{{ old('reference') }}" required maxlength="100"></div><div class="field"><label>Detail barang</label><input class="input" name="item_details" value="{{ old('item_details') }}" required maxlength="180"></div><div class="field"><label>Keterangan</label><input class="input" name="description_type" value="{{ old('description_type') }}" required maxlength="100"></div><div class="field"><label>Info</label><input class="input" name="info" value="{{ old('info') }}"></div><div class="field"><label>Negara</label><select class="select" name="country_id" required>@foreach($countries as $country)<option value="{{ $country->id }}">{{ $country->name }}</option>@endforeach</select></div><div class="field"><label>Tracking Number</label><input class="input" name="tracking_number" value="{{ old('tracking_number') }}"></div><div class="field"><label>Status</label><select class="select" name="status" required>@foreach(\App\Services\OrderStatusService::statuses() as $status)<option value="{{ $status }}">{{ \App\Services\OrderStatusService::label($status) }}</option>@endforeach</select></div><div class="field full"><label><input type="checkbox" name="visible_publicly" value="1" checked> Tampilkan publik</label></div></div><button class="btn btn-primary" style="margin-top:14px">Tambah tracking</button></form>
@endif
@endsection
