@extends('layouts.dashboard')
@section('title','Data Master')
@section('dashboard')
<div class="page-head"><div><div class="eyebrow">DATA MASTER</div><h1>Data operasional</h1><p class="muted">Shipping, warehouse, GO, rekening, dan status perjalanan dikelola terpisah dari Rate.</p></div></div>
<div class="grid grid-2">
<div class="card"><h3>Opsi shipping</h3>@foreach($countries as $country) @foreach($country->shippingOptions as $shipping)<div class="summary-row"><div><strong>{{ $shipping->label }}</strong><div class="small muted">{{ $country->name }} · {{ (float)$shipping->amount_foreign===0.0?'Free Shipping':$country->moneySymbol().number_format($shipping->amount_foreign,0,',','.') }}</div></div><form method="post" action="{{ route('owner.master.shipping.toggle',$shipping) }}" data-confirm="Ubah status opsi shipping ini?">@csrf<button class="btn btn-sm {{ $shipping->active?'btn-danger':'btn-soft' }}">{{ $shipping->active?'Nonaktifkan':'Aktifkan' }}</button></form></div>@endforeach @endforeach</div>
<form class="card" method="post" action="{{ route('owner.master.shipping') }}">@csrf<h3>Tambah shipping</h3><div class="field"><label>Negara</label><select class="select" name="country_id" required>@foreach($countries as $country)<option value="{{ $country->id }}">{{ $country->name }}</option>@endforeach</select></div><div class="field"><label>Label</label><input class="input" name="label" required></div><div class="field"><label>Nominal mata uang asal</label><input class="input" type="number" step="0.01" min="0" name="amount_foreign" required><div class="help">Isi 0 untuk Free Shipping.</div></div><button class="btn btn-primary">Tambah</button></form>
<div class="card"><h3>Warehouse</h3>@foreach($countries as $country) @foreach($country->warehouses as $w)<div class="summary-row"><div><strong>{{ $w->code }}</strong><div class="small muted">{{ $country->name }} · {{ $w->name }}</div></div></div>@endforeach @endforeach<form method="post" action="{{ route('owner.master.warehouse') }}" style="margin-top:14px">@csrf<div class="form-grid"><div class="field"><label>Negara</label><select class="select" name="country_id" required>@foreach($countries as $country)<option value="{{ $country->id }}">{{ $country->name }}</option>@endforeach</select></div><div class="field"><label>Kode</label><input class="input" name="code" required></div><div class="field"><label>Nama</label><input class="input" name="name"></div><div class="field"><label>Catatan</label><input class="input" name="notes"></div></div><button class="btn btn-primary">Tambah warehouse</button></form></div>
<div class="card"><h3>GO</h3>@foreach($groups as $g)<div class="summary-row"><strong>{{ $g->name }}</strong><span class="badge {{ $g->status==='active'?'ok':'gray' }}">{{ $g->status }}</span></div>@endforeach<form method="post" action="{{ route('owner.master.go') }}" style="margin-top:14px">@csrf<div class="field"><label>Nama GO</label><input class="input" name="name" required></div><div class="field"><label>Catatan</label><input class="input" name="notes"></div><button class="btn btn-primary">Tambah GO</button></form></div>
<div class="card" style="grid-column:1/-1"><div class="section-head"><div><h3>Rekening pembayaran</h3><p>Rekening aktif akan tampil sebagai pilihan wajib saat customer mengirim bukti pembayaran.</p></div></div><div class="bank-admin-list">@foreach($banks as $bank)<div class="bank-admin-card"><div><strong>{{ $bank->bank_name }} · {{ $bank->account_number }}</strong><div class="small muted">{{ $bank->account_name }}</div></div><div class="actions"><span class="badge {{ $bank->active?'ok':'gray' }}">{{ $bank->active?'Aktif':'Nonaktif' }}</span><form method="post" action="{{ route('owner.master.bank.toggle',$bank) }}" data-confirm="{{ $bank->active?'Nonaktifkan rekening ini? Rekening tidak akan bisa dipilih customer.':'Aktifkan rekening ini?' }}">@csrf<button class="btn btn-sm {{ $bank->active?'btn-danger':'btn-soft' }}">{{ $bank->active?'Nonaktifkan':'Aktifkan' }}</button></form></div></div>@endforeach</div><form method="post" action="{{ route('owner.master.bank') }}" style="margin-top:18px">@csrf<div class="form-grid"><div class="field"><label>Bank</label><input class="input" name="bank_name" required></div><div class="field"><label>Nomor rekening</label><input class="input" name="account_number" required></div><div class="field"><label>Nama pemilik</label><input class="input" name="account_name" required></div><div class="field"><label>Instruksi</label><input class="input" name="instructions"></div></div><button class="btn btn-primary">Tambah rekening</button></form></div>
<div class="card" style="grid-column:1/-1"><div class="section-head"><div><h3>Status perjalanan</h3><p>Label dan warna dapat disesuaikan. Status sistem tetap memakai kode internal agar otomatisasi tidak rusak.</p></div></div><div class="status-admin-grid">@foreach($statuses as $status)<form class="status-admin-card" method="post" action="{{ route('owner.master.status',$status) }}">@csrf<div class="status-preview"><span class="status-dot" style="background:{{ $status->color }}"></span><strong>{{ $status->label }}</strong><span class="small muted">{{ $status->code }}</span></div><div class="form-grid"><div class="field"><label>Nama status</label><input class="input" name="label" value="{{ $status->label }}" required></div><div class="field"><label>Warna</label><div class="color-control"><input type="color" name="color" value="{{ $status->color }}" required><span>{{ $status->color }}</span></div></div><div class="field"><label>Urutan</label><input class="input" type="number" name="sort_order" min="0" value="{{ $status->sort_order }}" required></div><div class="field">@if($status->system)<input type="hidden" name="active" value="1"><label><input type="checkbox" checked disabled> Aktif (status inti)</label>@else<label><input type="checkbox" name="active" value="1" @checked($status->active)> Aktif</label>@endif</div></div><button class="btn btn-soft btn-sm">Simpan status</button></form>@endforeach</div><form class="card card-blue" method="post" action="{{ route('owner.master.status') }}" style="margin-top:16px">@csrf<h3>Tambah status custom</h3><div class="form-grid"><div class="field"><label>Kode</label><input class="input" name="code" placeholder="quality_check" required></div><div class="field"><label>Nama status</label><input class="input" name="label" placeholder="Quality Check" required></div><div class="field"><label>Warna</label><input type="color" name="color" value="#2d63d7" required></div><div class="field"><label>Urutan</label><input class="input" type="number" name="sort_order" min="0" value="90" required></div><input type="hidden" name="active" value="1"></div><button class="btn btn-primary">Tambah status</button></form></div>
</div>
@endsection
