@extends('layouts.dashboard')
@section('title',$customer->name)
@section('dashboard')
<div class="page-head"><div><div class="eyebrow">CUSTOMER</div><h1>{{ $customer->name }}</h1><p class="muted">{{ str_ends_with($customer->email,'@placeholder.local')?'Belum terhubung akun':$customer->email }}</p></div><span class="badge {{ $customer->active?'ok':'gray' }}">{{ $customer->active?'Aktif':'Nonaktif' }}</span></div>
<div class="grid grid-2">
<div class="card"><h3>Kontak</h3><div class="summary-row"><span>Username</span><strong>{{ $customer->customerProfile?->username ?: '-' }}</strong></div><div class="summary-row"><span>WhatsApp</span><strong>{{ $customer->customerProfile?->whatsapp ?: '-' }}</strong></div><div class="summary-row"><span>LINE</span><strong>{{ $customer->customerProfile?->line_id ?: '-' }}</strong></div><div class="summary-row"><span>Sumber</span><strong>{{ $customer->customerProfile?->source_channel ?: '-' }}</strong></div></div>
<div class="card"><h3>Ringkasan</h3><div class="summary-row"><span>Order</span><strong>{{ $customer->orders->count() }}</strong></div><div class="summary-row"><span>Tagihan</span><strong>{{ $customer->invoices->count() }}</strong></div><div class="summary-row"><span>Sisa tagihan</span><strong>Rp{{ number_format($customer->invoices->sum(fn($i)=>$i->outstanding()),0,',','.') }}</strong></div></div>
<div class="card" style="grid-column:1/-1"><h3>Order terakhir</h3>@forelse($customer->orders->sortByDesc('created_at')->take(15) as $o)<div class="summary-row"><div><strong>{{ $o->order_number }}</strong><div class="small muted">{{ $o->items->first()?->item_name }}</div></div><a class="btn btn-soft btn-sm" href="{{ route('owner.orders.show',$o) }}">{{ \App\Services\OrderStatusService::label($o->status) }}</a></div>@empty<div class="empty">Belum ada order.</div>@endforelse</div>
@if(str_ends_with($customer->email,'@placeholder.local'))<div class="card" style="grid-column:1/-1"><h3>Gabungkan data legacy</h3><p class="small muted">Gunakan jika record hasil migrasi perlu dipindahkan ke akun customer yang sudah aktif.</p><form method="post" action="{{ route('owner.customers.merge',$customer) }}" data-confirm="Semua order, tagihan, dan pembayaran customer ini akan dipindahkan ke akun tujuan. Lanjutkan?">@csrf<div class="field" style="max-width:360px"><label>Email akun tujuan</label><input class="input" type="email" name="target_email" placeholder="customer@example.com" required></div><div class="actions" style="margin-top:12px"><button class="btn btn-danger">Gabungkan data</button></div></form></div>@endif
</div>
@endsection
